resources:
  - ../../../base/fill-profile

patches:
  - target:
      kind: Deployment
      name: fill-profile-deployment
    path: fill-profile-ms/deployment-patch.yaml

  - target:
      kind: Deployment
      name: redis-deployment
    path: redis/deployment-patch.yaml

namespace: fill-profile-dev
