apiVersion: v1
kind: Service
metadata:
  name: microservice-1
  namespace: my-nestjs-namespace
spec:
  selector:
    app: microservice-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
