apiVersion: apps/v1
kind: Deployment
metadata:
  name: fill-profile-deployment
  namespace: fill-profile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fill-profile
  template:
    metadata:
      labels:
        app: fill-profile
    spec:
      containers:
        - name: fill-profile
          image: sparkle788/auth:latest
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: '256Mi'
              cpu: '500m'
            limits:
              memory: '512Mi'
              cpu: '1000m'
          env:
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: fill-profile-config
                  key: SENTRY_DSN
            - name: USERS_DB_URL
              valueFrom:
                secretKeyRef:
                  name: fill-profile-secret
                  key: USERS_DB_URL
            - name: RT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fill-profile-secret
                  key: RT_SECRET
            - name: AT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fill-profile-secret
                  key: AT_SECRET
