apiVersion: v1
kind: Service
metadata:
  name: fill-profile-service
  namespace: fill-profile
spec:
  selector:
    app: fill-profile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
