apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
