apiVersion: v1
kind: Secret
metadata:
  name: fill-profile-secret
  namespace: fill-profile
type: Opaque
data:
  #base64 encoded secrets
  AT_SECRET: 'UWRqa0J4VjV2c3NVZDNqZm1vNW9lb1lCbmQybWV1b3A='
  RT_SECRET: 'Ynk0WUQzRVhUaGtDOFk3ODRkbmxuOFpYeExVYURtZUs='
  USERS_DB_URL: 'cG9zdGdyZXM6Ly9wb3N0Z3Jlcy5qc2Z0cXBqbWFyaXFyendydmVqbjpKZXQlNDBPTSUzRGNNNTFRJTI2MVpOS0tPMENLJTIzekNaVW1LS0s4QGF3cy0wLWV1LWNlbnRyYWwtMS5wb29sZXIuc3VwYWJhc2UuY29tOjY1NDMvcG9zdGdyZXM/cGdib3VuY2VyPXRydWU='
